force-app/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exercise_Item__c/Exercise_Item__c.object-meta.xml
<CustomObject>
    <label>Exercise Item</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Exercise Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exercise Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exercise_Item__c/fields/Calories_burned__c.field-meta.xml
<CustomField>
    <fullName>Calories_burned__c</fullName>
    <label>Calories burned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Exercise__c.field-meta.xml
<CustomField>
    <fullName>Exercise__c</fullName>
    <label>Exercise</label>
    <referenceTo>Exercise__c</referenceTo>
    <relationshipLabel>Exercise Items</relationshipLabel>
    <relationshipName>Exercise_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Exercise_Image__c.field-meta.xml
<CustomField>
    <fullName>Exercise_Image__c</fullName>
    <formula>Exercise__r.Image__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exercise Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Exercise_Name__c.field-meta.xml
<CustomField>
    <fullName>Exercise_Name__c</fullName>
    <formula>Exercise__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exercise Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Exercise_Video__c.field-meta.xml
<CustomField>
    <fullName>Exercise_Video__c</fullName>
    <formula>Exercise__r.Video__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exercise Video</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Rest__c.field-meta.xml
<CustomField>
    <fullName>Rest__c</fullName>
    <inlineHelpText>Rest in number</inlineHelpText>
    <label>Rest</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <inlineHelpText>Time in seconds</inlineHelpText>
    <label>Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Exercise_Item__c/fields/Workout__c.field-meta.xml
<CustomField>
    <fullName>Workout__c</fullName>
    <label>Workout</label>
    <referenceTo>Workout__c</referenceTo>
    <relationshipLabel>Exercise Items</relationshipLabel>
    <relationshipName>Exercise_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workout__c/Workout__c.object-meta.xml
<CustomObject>
    <label>Workout</label>
    <nameField>
        <label>Workout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Workout__c/fields/Main_muscle__c.field-meta.xml
<CustomField>
    <fullName>Main_muscle__c</fullName>
    <label>Main muscle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Arm</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
            <value>
                <fullName>Back and biceps</fullName>
            </value>
            <value>
                <fullName>Chest</fullName>
            </value>
            <value>
                <fullName>Chest and triceps</fullName>
            </value>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Leg</fullName>
            </value>
            <value>
                <fullName>Lower body</fullName>
            </value>
            <value>
                <fullName>Shoulder</fullName>
            </value>
            <value>
                <fullName>Upper body</fullName>
            </value>
            <value>
                <fullName>Whole body</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Total_calo_burned__c.field-meta.xml
<CustomField>
    <fullName>Total_calo_burned__c</fullName>
    <description>Sum total calories burned from all inclusive exercises</description>
    <inlineHelpText>Sum total calories burned from all inclusive exercises (for one set only)</inlineHelpText>
    <label>Total calo burned</label>
    <summarizedField>Exercise_Item__c.Calories_burned__c</summarizedField>
    <summaryForeignKey>Exercise_Item__c.Workout__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Total_calo_burned_all_sets__c.field-meta.xml
<CustomField>
    <fullName>Total_calo_burned_all_sets__c</fullName>
    <formula>Total_calo_burned__c *  Total_Set__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total calories burned (all sets)</inlineHelpText>
    <label>Total calo burned all sets</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Total_Set__c.field-meta.xml
<CustomField>
    <fullName>Total_Set__c</fullName>
    <label>Total Set</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workout__c/fields/Total_workout_time_all_set__c.field-meta.xml
<CustomField>
    <fullName>Total_workout_time_all_set__c</fullName>
    <formula>( Total_workout_time__c +  Total_rest_time__c ) *  Total_Set__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Total workout time for all set (rest included)</inlineHelpText>
    <label>Total workout time all set</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workout_Activity__c/Workout_Activity__c.object-meta.xml
<CustomObject>
    <label>Workout Activity</label>
    <nameField>
        <displayFormat>WA-{0000}</displayFormat>
        <label>Workout Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workout Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workout_Activity__c/fields/Total_calo_burned__c.field-meta.xml
<CustomField>
    <fullName>Total_calo_burned__c</fullName>
    <label>Total calo burned</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workout_Activity__c/fields/Total_time__c.field-meta.xml
<CustomField>
    <fullName>Total_time__c</fullName>
    <label>Total time (in seconds)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workout_Activity__c/fields/Total_time_formatted__c.field-meta.xml
<CustomField>
    <fullName>Total_time_formatted__c</fullName>
    <label>Total time</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workout_Activity__c/fields/Workout__c.field-meta.xml
<CustomField>
    <fullName>Workout__c</fullName>
    <description>The workout done within this activity.</description>
    <label>Workout</label>
    <referenceTo>Workout__c</referenceTo>
    <relationshipLabel>Workout Activities</relationshipLabel>
    <relationshipName>Workout_Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/WorkoutController.cls
public class WorkoutController {
    @RemoteAction
    @AuraEnabled
    public static Workout__c getWorkout (string id) {
        List<Workout__c> workouts = [select Id, 
                                     Name, 
                                     Main_muscle__c, 
                                     Total_Set__c , 
                                     Total_workout_time_all_set__c, 
                                     Total_calo_burned__c, 
                                     Total_calo_burned_all_sets__c, 
                                     (select Id, Name, 
                                      Exercise__c,
                                      Exercise_Name__c, 
                                      Exercise_Image__c, 
                                      Exercise_Video__c, 
                                      Rest__c, Time__c, 
                                      Calories_burned__c 
                                      from Exercise_Items__r) 
                                    from Workout__c 
                                    where Id = :id];
        
        Workout__c thisWorkout = null;
        if(workouts.size() > 0) {
            thisWorkout = workouts.get(0);
            return thisWorkout;
        } else {
            return null;
        }
    }
    
    @RemoteAction
    @AuraEnabled
    public static Workout_Activity__c saveWorkoutActivity(Decimal totalTime, 
                                                          Decimal totalCalo, 
                                                          String totalTimeFormatted, 
                                                          string workoutId) {
                                                              
        Workout_Activity__c newWorkoutActivity = new Workout_Activity__c();
        newWorkoutActivity.Total_calo_burned__c = totalCalo;
        newWorkoutActivity.Total_time__c = totalTime;
        newWorkoutActivity.Workout__c = workoutId;
        newWorkoutActivity.Total_time_formatted__c = totalTimeFormatted;
        
        try {
            insert newWorkoutActivity;
            return newWorkoutActivity;
        } catch(DmlException e) {
            system.debug('Cannot save workout activity: ' + e.getMessage());
            return null;
        }
    }

}