force-app/main/default/objects/Exercise__c/Exercise__c.object-meta.xml
<CustomObject>
    <label>Exercise</label>
    <nameField>
        <label>Exercise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exercises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exercise__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExerciseController.cls
public class ExerciseController {
	@RemoteAction
    @AuraEnabled
    public static string getExerciseImg (string id) {
        List<Exercise__c> exercises = [select Id, Image__c
                               from Exercise__c 
                               where Id =: id];
        
        Exercise__c thisExercise = null;
        if(exercises.size() > 0) {
            thisExercise = exercises.get(0);
            return thisExercise.Image__c;
        } else {
            return '';
        }
    }
    
    @RemoteAction
    @AuraEnabled
    public static string getExerciseVideo (string id) {
        List<Exercise__c> exercises = [select Id, Video__c
                               from Exercise__c 
                               where Id =: id];
        
        Exercise__c thisExercise = null;
        if(exercises.size() > 0) {
            thisExercise = exercises.get(0);
            return thisExercise.Video__c;
        } else {
            return '';
        }
    }
}